spring:
  jpa:
    generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            clientSecret:


management:
  endpoints:
    web:
      exposure:
        include: "*"



---
spring:
  profiles: mysql
  datasource:
    url: "jdbc:mysql://localhost/music"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
